#! /usr/bin/env python3
import sys
import argparse
import ntm_profiler as ntmp
import os
import pathogenprofiler as pp
from uuid import uuid4
import json
import glob
import atexit

__softwarename__ = "ntm-profiler"

@atexit.register
def cleanup():
    if "last_traceback" in vars(sys):
        if args.files_prefix and not args.no_clean:
            sys.stderr.write("Cleaning up after failed run\n")
            for f in glob.glob(args.files_prefix+"*"):
                os.remove(f)
        import traceback
        
        if "prefix" in vars(args):
            outfile = "%s.errlog" % args.prefix
        elif "vcf" in vars(args):
            outfile = "%s.errlog" % args.vcf.split("/")[-1]
        elif "outfile" in vars(args):
            outfile = "%s.errlog" % args.outfile
        else:
            outfile = "%s.errlog" % uuid4()
        with open(outfile, "w") as O:
            O.write("# ntm-profiler error report\n\n")
            O.write("* OS: %s\n" % sys.platform)
            O.write("* Program version: %s\n" % ntmp.__version__)
            O.write("* Database version: %s\n" % json.load(open(args.conf["version"]))["commit"]) if "conf" in vars(args) else ""
            O.write("* Program call:\n")
            O.write("```\n")
            O.write("%s\n" % vars(args))
            O.write("```\n")

            O.write("## Traceback:\n")
            O.write("```\n")
            traceback.print_tb(sys.last_traceback,file=O)
            O.write("```\n")

            O.write("## Value:\n")
            O.write("```\n")
            O.write("%s" % sys.last_value)
            O.write("```\n")
        pp.errlog("""\n
################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/NTM-Profiler/issues/new and paste or attach the
contents of the error log (%s)

###############################################################################
""" % (outfile))



def main_profile(args):
    if args.external_resistance_db:
        args.resistance_db = args.external_resistance_db
    if args.external_species_db:
        args.species_db = args.external_species_db


    ### Create folders for results if they don't exist ###
    if pp.nofolder(args.dir):
        os.mkdir(args.dir)

    if args.vcf:
        args.no_species = True
        if not args.resistance_db:
            pp.errlog(
                "\nSpeciation can't be perfomrmed on a VCF file so a resistance database is needed. "
                "Specify with --resistance_db or --external_resistance_db\n",
                ext=True
            )
    
    results = {
        "id":args.prefix,
        "software_version":ntmp.__version__
    }
    if not args.no_species:
        species_prediction = pp.speciate(args)
    else:
        species_prediction = None
    
    results.update({
        "species": species_prediction,
        "pipeline_software": [{"Analysis":"Kmer counting","Program":"kmc"}]
    })

    if args.species_only:
        args.conf = None
        ntmp.write_outputs(args,results)
        pp.run_cmd(f"rm {args.files_prefix}*")
        pp.successlog("Species prediction finished!")
        quit(0)


    args.conf = pp.get_resistance_db_from_species_prediction(args,species_prediction)
    if args.conf is None:
        ntmp.write_outputs(args,results)

    
    args = pp.set_platform_params(args)
    
    # Legacy compatibility
    args.missing_cov_threshold = args.min_depth

    results.update(pp.run_profiler(args))


    results["resistance_genes"] = ntmp.test_resistance_genes(args.conf,results)
    

    results["pipeline_software"].extend([
        {"Analysis":"Mapping","Program": args.mapper if not args.bam else "N/A"},
        {"Analysis":"Variant calling","Program":args.caller}
    ])
    results["resistance_db_version"] = json.load(open(args.conf["version"]))

    results = ntmp.reformat(results,args.conf)

    ntmp.write_outputs(args,results)

    ### Move files to respective directories ###
    result_files = {
        "%s.delly.bcf" % args.files_prefix: "%s/%s.delly.bcf" % (args.dir,args.prefix),
        "%s.targets.csq.vcf.gz" % args.files_prefix: "%s/%s.targets.csq.vcf.gz" % (args.dir,args.prefix),
        "%s.vcf.gz" % args.files_prefix: "%s/%s.vcf.gz" % (args.dir,args.prefix),
        "%s.bam" % args.files_prefix: "%s/%s.bam" % (args.dir,args.prefix),
        "%s.bam.bai" % args.files_prefix: "%s/%s.bam.bai" % (args.dir,args.prefix),
    }

    for file,target in result_files.items():
        if os.path.isfile(file):
            os.rename(file,target)

    pp.run_cmd(f"rm {args.files_prefix}*")





def create_species_db(args):
    pp.create_species_db(args)

def create_resistance_db(args):
    pp.create_db(args,extra_files=[])


def main_collate(args):
    ntmp.collate(args)


def main_update_db(args):
    if os.path.isdir('ntmdb'):
        os.chdir('ntmdb')
        pp.run_cmd('git pull')
        os.chdir('db/')
    else:
        pp.run_cmd('git clone https://github.com/jodyphelan/ntmdb.git')
        os.chdir('ntmdb/db/')
    dirs = [d for d in os.listdir() if os.path.isdir(d)]
    pp.infolog('\nCreating species DB')
    pp.run_cmd('ntm-profiler create_species_db -p ntmdb --kmers ntm_db.kmers.txt --load')
    for d in dirs:
        os.chdir(d)
        for species in json.load(open('variables.json'))['species']:
            pp.infolog(f'\nCreating DB for {species}')
            pp.run_cmd(f'ntm-profiler create_resistance_db --prefix {species.replace(" ","_")} --csv resistance_variants.csv --load')
        os.chdir('../')



#### Argument Parsing ####

parser = argparse.ArgumentParser(description='NTM-Profiler pipeline',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
parser.add_argument('--no_clean', action='store_true', help=argparse.SUPPRESS)
subparsers = parser.add_subparsers(help="Task to perform")


###### Profile #######
parser_sub = subparsers.add_parser('profile', help='Run whole profiling pipeline', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
input=parser_sub.add_argument_group("Input options")
group = input.add_mutually_exclusive_group(required=True)
group.add_argument('--read1','-1',help='First read file')
input.add_argument('--read2','-2',help='Second read file')
group.add_argument('--bam','-a',help='BAM file. Make sure it has been generated using the H37Rv genome (GCA_000195955.2)')
group.add_argument('--fasta','-f',help='Fasta file')
group.add_argument('--vcf',help='VCF file')
input.add_argument('--platform','-m',choices=["illumina","nanopore"],default="illumina",help='NGS Platform used to generate data')
input.add_argument('--resistance_db',help='Mutation panel name')
input.add_argument('--external_resistance_db',type=str,help='Path to db files prefix (overrides "--db" parameter)')
input.add_argument('--species_db',default='ntmdb',help='Mutation panel name')
input.add_argument('--external_species_db',type=str,help='Path to db files prefix (overrides "--db" parameter)')

output=parser_sub.add_argument_group("Output options")
output.add_argument('--prefix','-p',default="ntmprofiler",help='Sample prefix for all results generated')
output.add_argument('--dir','-d',default=".",help='Storage directory')
output.add_argument('--csv',action="store_true",help="Add CSV output")
output.add_argument('--txt',action="store_true",help="Add text output")
# output.add_argument('--pdf',action="store_true",help="Add PDF output. This requires pdflatex to be installed")
output.add_argument('--add_columns',default=None,type=str,help="Add additional columns found in the mutation database to the text and csv results")
output.add_argument('--add_mutation_metadata',action="store_true",help=argparse.SUPPRESS)
output.add_argument('--call_whole_genome',action="store_true",help="Call whole genome")

algorithm=parser_sub.add_argument_group("Algorithm options")
algorithm.add_argument('--mapper',default="bwa", choices=["bwa","minimap2","bowtie2","bwa-mem2"],help="Mapping tool to use. If you are using nanopore data it will default to minimap2",type=str)
algorithm.add_argument('--caller',default="freebayes", choices=["bcftools","gatk","freebayes"],help="Variant calling tool to use.",type=str)
algorithm.add_argument('--calling_params',type=str,help='Override default parameters for variant calling')
algorithm.add_argument('--min_depth',default=10,type=int,help='Minimum depth required to call variant. Bases with depth below this cutoff will be marked as missing')
algorithm.add_argument('--af',default=0.1,type=float,help='Minimum allele frequency to call variants')
algorithm.add_argument('--reporting_af',default=0.1,type=float,help='Minimum allele frequency to use variants for prediction')
algorithm.add_argument('--coverage_fraction_threshold',default=0,type=int,help='Cutoff used to calculate fraction of region covered by <= this value')
algorithm.add_argument('--missing_cov_threshold',type=int,help='Cutoff used to positions/codons in genes which are missing (this argument has now been merged with --min_depth argument and will be deprecated in future releases)')
algorithm.add_argument('--species_only',action="store_true",help="Predict species and quit")
algorithm.add_argument('--no_trim',action="store_true",help="Don't trim files using trimmomatic")
algorithm.add_argument('--no_flagstat',action="store_true",help="Don't collect flagstats")
algorithm.add_argument('--no_clip',action="store_false",help="Don't clip reads")
algorithm.add_argument('--no_delly',action="store_true",help="Don't run delly")
algorithm.add_argument('--no_species',action="store_true",help=argparse.SUPPRESS)
algorithm.add_argument('--output_kmer_counts',action="store_true",help=argparse.SUPPRESS)
algorithm.add_argument('--add_variant_annotations',action="store_true",help=argparse.SUPPRESS)
algorithm.add_argument('--threads','-t',default=1,help='Threads to use',type=int)

other=parser_sub.add_argument_group("Other options")
other.add_argument('--verbose','-v',default=0, choices=[0,1,2],help="Verbosity increases from 0 to 2",type=int)
other.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
other.add_argument('--no_cleanup',action="store_true",help="Don't remove temporary files on error")
other.add_argument('--delly_vcf',help=argparse.SUPPRESS)
parser_sub.set_defaults(func=main_profile)






# Collate results #
parser_sub = subparsers.add_parser('collate', help='Collate results form multiple samples together', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--outfile','-o',default="ntmprofiler.collate.txt",help='Sample prefix')
parser_sub.add_argument('--samples',help='File with samples (one per line)')
parser_sub.add_argument('--dir','-d',default=".",help='Storage directory')
parser_sub.add_argument('--suffix',default=".results.json",type=str,help='Input results files suffix')
parser_sub.add_argument('--format',default="txt",choices=["txt","csv"],type=str,help='Output file type')
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
parser_sub.set_defaults(func=main_collate)





# Update database #
parser_sub = subparsers.add_parser('update_db', help='Update all databases', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
parser_sub.add_argument('--dir','-d',default=".",help='Storage directory')
parser_sub.set_defaults(func=main_update_db)




# Create resistance DB #
parser_sub = subparsers.add_parser('create_resistance_db', help='Generate the files required to run resistance profiling with NTM-Profiler', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The name of the database (match species name for automated speciation+resistance detection)',required = True)
parser_sub.add_argument('--csv','-c',type=str,help='The CSV file containing mutations')
parser_sub.add_argument('--load',action="store_true",help='Load the library after creating it')
parser_sub.add_argument('--watchlist','-w',type=str,help='A csv file containing genes to profile but without any specific associated mutations')
parser_sub.add_argument('--match_ref',type=str,help='The prefix for all output files')
parser_sub.add_argument('--other_annotations',type=str,help='The prefix for all output files')
parser_sub.add_argument('--custom',action="store_true",help='Tells the script this is a custom database, this is used to alter the generation of the version file')
parser_sub.add_argument('--db-name',help='Overrides the name of the database in the version file')
parser_sub.add_argument('--db-commit',help='Overrides the commit string of the database in the version file')
parser_sub.add_argument('--db-author',help='Overrides the author of the database in the version file')
parser_sub.add_argument('--db-date',help='Overrides the date of the database in the version file')
parser_sub.add_argument('--include_original_mutation',action="store_true", help='Include the original mutation (before reformatting) as part of the variant annotaion')
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
parser_sub.add_argument('--dir','-d',default=".",help='Storage directory')
parser_sub.set_defaults(func=create_resistance_db)



parser_sub = subparsers.add_parser('create_species_db', help='Generate the files required to run speciation with NTM-Profiler', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The name of the database',required = True)
parser_sub.add_argument('--kmers',type=str,help='The file containing species specific kmers',required = True)
parser_sub.add_argument('--load',action="store_true",help='Load the library after creating it',required = True)
parser_sub.add_argument('--db-name',help='Overrides the name of the database in the version file')
parser_sub.add_argument('--db-commit',help='Overrides the commit string of the database in the version file')
parser_sub.add_argument('--db-author',help='Overrides the author of the database in the version file')
parser_sub.add_argument('--db-date',help='Overrides the date of the database in the version file')
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % ntmp.__version__)
parser_sub.add_argument('--dir','-d',default=".",help='Storage directory')
parser_sub.set_defaults(func=create_species_db)



args = parser.parse_args()
if hasattr(args, 'func'):
    args.software_name = __softwarename__
    args.tmp_prefix = str(uuid4())
    args.files_prefix = args.dir+"/"+args.tmp_prefix

    args.func(args)
else:
    parser.print_help(sys.stderr)